baseurl = "https://degangwang.com"
title = "Degang Wang"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
timeZone = "America/Chicago"
preserveTaxonomyNames = true
hasCJKLanguage = true

[services]
  # Enable comments by entering your Disqus shortname
  [services.disqus]
    shortname = ""
  [services.googleAnalytics]
    id = ""

[pagination]
  pagerSize = 5 # frontpage pagination

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-grass.jpg"
  SEOTitle = "Degang Blog"
  slogan = "Every blade of grass has its own dew"
  upstreamAttribution = false

  image_404 = "img/404-bg.png"
  title_404 = "Page not found :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_counter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = "SX4D8449TR"
  algolia_indexName = "degang-blog"
  algolia_apiKey = "71c58b12e2d35a6503b62ca98d83d429"

  # Sidebar settings
  sidebar_about_description = "Degang Wang (汪德刚), working at the intersection of RWD, epidemiology, biostatistics, and modern data platforms."
  sidebar_avatar = "img/degang-r.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 0

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = ""

  # Artalk comments
  # Follow https://artalk.js.org/ to set up your own server
  # artalk_enable = true
  # artalk_server = "https://xxx.xxx.com"
  # artalk_site = "xxx blog"

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = false 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = false
  bookmarks = true
  about_me = true

  # Last posts
  last_posts = true
  #last_posts_title = "LAST POSTS"
  #last_posts_count = 5

  # Include any custom CSS and/or JS files, url or relative to /static folder
  custom_css = ["css/custom.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.giscus]
  data_repo="wangdegang/Blog"
  data_repo_id="R_kgDOSWNKdg"
  data_category="Announcements"
  data_category_id="DIC_kwDOSWNKds4C8fD_"
  data_mapping="pathname"
  data_reactions_enabled="1"
  data_emit_metadata="0"
  data_theme="light"
  data_lang="en"
  crossorigin="anonymous"

  [params.social]
  rss            = true 
  email          = "dgwang7@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = "https://www.linkedin.com/in/degang-wang/"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/wangdegang"
  wechat         = "img/wechat_qrcode.jpg"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  [[params.friend_link]]
  title = "Linda的博客"
  href =  "https://zhaozhihan.com"

  [[params.bookmark_link]]
  title =  "FDA"
  href =  "https://www.fda.gov/science-research/science-and-research-special-topics/real-world-evidence"
  [[params.bookmark_link]]
  title = "ISPOR"
  href =  "https://www.ispor.org/home"
  [[params.bookmark_link]]
  title =  "Google Scholar"
  href =  "https://scholar.google.com/scholar_labs/search?hl=en"
  
  [[params.additional_menus]]
  title =  "ARCHIVE"
  href =  "/archive/"
  [[params.additional_menus]]
  title =  "ABOUT"
  href =  "/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[mediaTypes]
  [mediaTypes.'font/woff']
    suffixes = ['woff']
  [mediaTypes.'font/woff2']
    suffixes = ['woff2']
